import localFont from "next/font/local";
import "./globals.css";
import React from "react";
import NavBar from "./components/navBar";
import ClientProviders from "./components/ClientProviders";
import { getUser } from "@/utils/dal";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // Récupérer l'utilisateur connecté côté serveur pour l'hydratation
  let initialUser = null;
  try {
    initialUser = await getUser();
    if (initialUser) {
      const { password_user, ...userWithoutPassword } = initialUser.toJSON();
      initialUser = userWithoutPassword;
    }
  } catch (error) {
    // Pas d'utilisateur connecté ou erreur, initialUser reste null
    console.log("No user session found");
  }

  return (
    <html lang="en" className="hide-scrollbar" suppressHydrationWarning={true}>
      <script
        dangerouslySetInnerHTML={{
          __html: `
            (function() {
              try {
                var theme = localStorage.getItem('theme');
                var systemTheme = window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
                var finalTheme = theme || systemTheme;
                
                if (finalTheme === 'dark') {
                  document.documentElement.classList.add('dark');
                } else {
                  document.documentElement.classList.remove('dark');
                }
              } catch (e) {
                // Fallback en cas d'erreur
                console.warn('Theme detection failed:', e);
              }
            })();
          `,
        }}
      />
      <script src="//unpkg.com/react-scan/dist/auto.global.js" async></script>
      <body
        className={
          `${geistSans.variable} ${geistMono.variable} antialiased` +
          " dark:bg-gray-900 bg-gray-100 text-gray-900 dark:text-gray-100"
        }
      >
        <ClientProviders initialUser={initialUser}>
          <div className="fixed top-0 left-0 right-0 z-50">
            <NavBar />
          </div>
          {children}
        </ClientProviders>
      </body>
    </html>
  );
}
