import localFont from "next/font/local";
import "./globals.css";
import React from "react";
import NavBar from "./components/navBar";
import { ThemeProvider } from "@/utils/themeContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="hide-scrollbar">
      <script src="//unpkg.com/react-scan/dist/auto.global.js" async></script>
      <body
        className={
          `${geistSans.variable} ${geistMono.variable} antialiased` +
          " dark:bg-gray-900 bg-gray-100 text-gray-900 dark:text-gray-100"
        }
      >
        <ThemeProvider>
          <div className="fixed top-0 left-0 right-0 z-50">
            <NavBar />
          </div>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
